version: '2'
services:
  web:
    build: .
    container_name: my-store
    volumes:
      - .:/var/www/html
    ports:
      - 8050:80
    depends_on:
      - db
    links:
      - db:store-db
  db:
    build:
      context: ./my-db
    image: store-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: oshry
      MYSQL_PASSWORD: oshry81
      MYSQL_DATABASE: my_db
    ports:
      - 3309:3306
    volumes:
      - ./my-db:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: store-phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=oshry81
    links:
      - db:store-db
    ports:
      - "8051:80"
